version: "3.5"

services:
  db:
    image: postgres:alpine
    container_name: work-postgres
    ports:
      - "5111:5432"
    networks:
      - main
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "password"


#  web:
#    build: .
#    command: bash -c "python manage.py makemigrations core && python manage.py makemigrations &&  python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8114"
#    container_name: work-web
#    volumes:
#      - .:/code
#    ports:
#      - "8114:8114"
#    depends_on:
#      - db
#    networks:
#      - main
#    environment:
#      DJANGO_SETTINGS_MODULE: "core.settings"
#      DEBUG: "True"


networks:
  main:
