version: "3.5"

services:
  db:
    image: postgres:alpine
    container_name: work-postgres
    expose:
      - 5432
    networks:
      - main
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "password"


  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8115"
    container_name: work-web
    volumes:
      - .:/code
    ports:
      - "80:8115"
    depends_on:
      - db
    networks:
      - main
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
      DEBUG: "True"


networks:
  main:
