version: "3.5"

services:
  db:
    image: postgres:alpine
    container_name: work-postgres
    ports:
      - "5111:5432"
    networks:
      - main
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "password"


networks:
  main:
